### ISSUE TITLE
Compiling with CMake

### ISSUE THREAD

**Issue by agoscinski** [Luthaf/rascaline#1]
Not sure if it is supposed to work at this stage, since the cargo build seems to work

configuring cmake gives me
```
 CMake Error at CMakeLists.txt:52 (message):
   your Rust installation is too old (version cargo 1.46.0

   ), at least 1.43.0 is required
```
I switched VERSION_LESS to LESS here
```
if ( ${REQUIRED_RUST_VERSION} VERSION_LESS ${CARGO_VERSION})
    message(FATAL_ERROR
        "your Rust installation is too old (version ${CARGO_VERSION}), at least \
        ${REQUIRED_RUST_VERSION} is required"
    )
endif()
```

Then the next error
```
 CMake Error at CMakeLists.txt:82 (target_include_directories):
   Cannot specify include directories for imported target "rascaline".
```
For digging into cmake it is a bit too late for me today

**Comment by Luthaf** [comment]
This should be working, but the condition on version is reversed (should be `${CARGO_VERSION} VERSION_LESS ${REQUIRED_RUST_VERSION}`). 

The imported target error is a bit strange, maybe something about cmake version? Which cmake do you have?

**Comment by Luthaf** [comment]
About the imported target: you have cmake 3.10 on cosmopc21, and support for adding INTERFACE include directory on imported targets was added on cmake 3.11 (cf https://cmake.org/cmake/help/v3.11/command/target_include_directories.html). I'll update compatibility bounds accordingly.
