### ISSUE TITLE
Rascaline wrapper for a Clebsch–Gordan functions

### ISSUE THREAD

**Issue by PicoCentauri** [Luthaf/rascaline#160]
As discussed in the dev-meeting:

PR #158 adds a pure Pythons implementation for constructing a Power-Spectrum for one or two Spherical Expansions. However, this is only a special case for Clebsch–Gordan function. We should try to generalize this a bit more and also focus on speed.

We had an idea for using an external library for the actual calculation and providing a wrapper for the rascaline style. @serfg could maybe share some more details here?

**Comment by Luthaf** [comment]
Closing in favor of #178 which tracks the same thing.
