### ISSUE TITLE
`RascalError: internal error: matrix is not invertible` for Si decohesion frames.

### ISSUE THREAD

**Issue by jwa7** [Luthaf/rascaline#215]
Using the dataset from Gabor Csanyi et al., DOI: https://doi.org/10.1103/physrevx.8.041048, for some of the decohesion frames, I get the above rascal error when computing the SphericalExpansion.

The original raw data can be obtained from https://www.repository.cam.ac.uk/items/1cfce189-65c3-4e05-a430-ba062a787802. With respect to the total set of frames from gp_iter6_sparse9k.xml.xyz, the indices of the offending frames are `[2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169]`, and I have attached these in an xyz.

To narrow down the problem: it appears that in the offending frames, but not in the rest, the Z-cell vector has a single large negative component. Any ideas as to why rascaline doesn't like this?

Tagging @SanggyuChong as we experienced this problem together.

[failed.xyz.zip](https://github.com/Luthaf/rascaline/files/12319958/failed.xyz.zip)

**Comment by ceriottm** [comment]
Z-cell would be the cell matrix? That might be a red herring, negative eigenvalues don't imply it can't be inverted

**Comment by Luthaf** [comment]
I was checking the determinant to make sure the matrix can be inverted, but assumed that the determinant could not be negative. Looks like I was wrong, ASE is happy with such cells and can we can even compute a neighbours list fine for them.
