### ISSUE TITLE
REMatch kernel

### ISSUE THREAD

**Issue by stenczelt** [Luthaf/rascaline#236]
@ceriottm / @Luthaf Is the REMatch kernel from https://arxiv.org/abs/1601.04077 implemented in this repo? If not, where is it and how to use it from Python?

**Comment by ceriottm** [comment]
It is not. You can find a python implementation here https://github.com/lab-cosmo/glosim/blob/master/libmatch/structures.py, but I can't say it's well documented. If you are willing to put in some effort to contribute, it's be really cool to add the rematch calculation in a clean, modular way here https://github.com/scikit-learn-contrib/scikit-matter

**Comment by Luthaf** [comment]
This repo only computes the representations, it does nothing special with them. If you want to compute the classic SOAP power spectrum, we have an example here: https://luthaf.fr/rascaline/latest/how-to/computing-soap.html. This will give you per-atom features. 

If you want per-structure features, you can use [`metatensor.sum_over_samples`](https://lab-cosmo.github.io/metatensor/latest/reference/operations/manipulation/samples-reduction.html#metatensor.sum_over_samples) after installing metatensor-operations (for now, you'll have to install it from the Github repo).

Let us know if anything is not clear, we are still working on the documentation!
