### ISSUE TITLE
SphericalBesselBasis normalization

### ISSUE THREAD

**Issue by frostedoyster** [Luthaf/rascaline#258]
While working on #257, I found some issues that look connected with the fact that the spherical Bessel basis is being orthonormalized. For moderate and high l_max, I there are numerical issues and scipy outputs warnings, and for l_max as low as 2 the consistency tests against `torch_spex` fail. I think we should disable the numerical orthonormalization for that basis since it's already orthonormal. Is there a way to do so? @PicoCentauri

**Comment by PicoCentauri** [comment]
@frostedoyster found an issue with the root searching for the bessel base. It will be fixed by #257.
