### ISSUE TITLE
Deepcopy fails on `rascaline.torch` calculators

### ISSUE THREAD

**Issue by frostedoyster** [Luthaf/rascaline#265]
When trying to deepcopy a calculator, I got
```
y = copier(memo)
RuntimeError: invalid parameter: unknown calculator with name 'SOAP power spectrum'
```
I am not sure if we want to support this, but just sharing the error

**Comment by Luthaf** [comment]
This should have been fixed by https://github.com/Luthaf/rascaline/commit/fca103ec4f975a7fcba521d2b0c27d582d2cbd7f. Are you using the latest version of rascaline?

If yes, please share a full example reproducing the issue.

**Comment by frostedoyster** [comment]
Perfect, my bad. I'm probably using an older version
