### ISSUE TITLE
prebuilt wheel still uses equistore

### ISSUE THREAD

**Issue by bananenpampe** [Luthaf/rascaline#279]
Hello, 

the wheel `pip install --extra-index-url https://luthaf.fr/temporary-wheels/ rascaline` points to, still uses equistore as a dependency.

**Comment by Luthaf** [comment]
Are you sure about that? The files in there have the right dependencies. Could you share the whole output of `pip install --verbose --extra-index-url https://luthaf.fr/temporary-wheels/ rascaline`?

I'm wondering if pip caching is killing us again.
